



class Ui_Form(object):
    def setupUi(self, widget):
        now = datetime.now()
        widget.resize(1700, 1200)
        widget.setWindowIcon(QIcon("icons/icon.ico"))
        widget.setToolTipDuration(-1)
        widget.setStyleSheet(u"QPushButton:hover{\n""background-color: silver;\n""}")
        # SHOW CHART BUTTON
        self.chartBtn = QPushButton(widget)
        self.chartBtn.setObjectName(u"chartBtn")
        self.chartBtn.setGeometry(QRect(1320, 20, 250, 110))
        self.chartBtn.setStyleSheet(u"background: lightgreen;\n""color: white;\n""font-size: 40px;")
        # SELECT TYPES CHARTS
        self.TypesCharts = QComboBox(widget)
        self.TypesCharts.setGeometry(QRect(1350, 150, 200, 40))
        self.TypesCharts.setStyleSheet(u"font-size: 30px;")
        self.TypesCharts.addItem("общая")
        self.TypesCharts.addItem("по времени")
        self.TypesCharts.addItem("по типам")
        self.TypesCharts.addItem("по продуктам")
        # TAB WIDGET EXPENSES AND INCOME
        self.MainTab = QTabWidget(widget)
        self.MainTab.setGeometry(10,10,1180,1110)
        # TEBLE EXPENSES
        self.tableExpenses = QTableWidget(widget)
        if (self.tableExpenses.columnCount() < 4):
            self.tableExpenses.setColumnCount(4)
        if (self.tableExpenses.rowCount() < 1000):
            self.tableExpenses.setRowCount(1000)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableExpenses.setItem(0, 0, __qtablewidgetitem)
        self.tableExpenses.setObjectName(u"tableWidget")
        self.tableExpenses.setGeometry(QRect(5, 5, 1180, 1110))
        self.tableExpenses.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableExpenses.setAutoScroll(True)
        self.tableExpenses.setRowCount(1000)
        self.tableExpenses.setColumnCount(4)
        self.tableExpenses.horizontalHeader().setCascadingSectionResizes(True)
        self.tableExpenses.horizontalHeader().setMinimumSectionSize(0)
        self.tableExpenses.horizontalHeader().setDefaultSectionSize(263)
        self.tableExpenses.verticalHeader().setDefaultSectionSize(50)
        self.tableExpenses.setStyleSheet(u"font-size: 30px;")
        # TEBLE INCOME
        self.tableIncome = QTableWidget(widget)
        if (self.tableIncome.columnCount() < 4):
            self.tableIncome.setColumnCount(4)
        if (self.tableIncome.rowCount() < 1000):
            self.tableIncome.setRowCount(1000)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableIncome.setItem(0, 0, __qtablewidgetitem)
        self.tableIncome.setObjectName(u"tableWidget")
        self.tableIncome.setGeometry(QRect(5, 5, 1180, 1110))
        self.tableIncome.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableIncome.setAutoScroll(True)
        self.tableIncome.setRowCount(1000)
        self.tableIncome.setColumnCount(4)
        self.tableIncome.horizontalHeader().setCascadingSectionResizes(True)
        self.tableIncome.horizontalHeader().setMinimumSectionSize(0)
        self.tableIncome.horizontalHeader().setDefaultSectionSize(263)
        self.tableIncome.verticalHeader().setDefaultSectionSize(50)
        self.tableIncome.setStyleSheet(u"font-size: 30px;")

        # ADD TAB TO TabWidget FOR EXPENSES AND INCOME
        self.MainTab.addTab(self.tableExpenses, "Расходы")
        self.MainTab.addTab(self.tableIncome, "Доходы")
        #self.MainTab.addTab(ChartsTab(), "Диаграмы")
        # TOTAL EXPENSES AND INCOME LABEL
        self.TotalLabel = QLabel(widget)
        self.TotalLabel.setObjectName(u"TypeLabel")
        self.TotalLabel.setGeometry(QRect(10, 1130, 1000, 60))
        self.TotalLabel.setStyleSheet(u"font-size: 39px;")
        # TOTAL LABEL
        self.TotalLabel_2 = QLabel(widget)
        self.TotalLabel_2.setObjectName(u"TypeLabel")
        self.TotalLabel_2.setGeometry(QRect(550, 1130, 1000, 60))
        self.TotalLabel_2.setStyleSheet(u"font-size: 39px;")

        self.percentTotalLabel = QLabel(widget)
        self.percentTotalLabel.setObjectName(u"TypeLabel")
        self.percentTotalLabel.setGeometry(QRect(850, 1130, 1000, 60))
        self.percentTotalLabel.setStyleSheet(u"font-size: 39px;\n""color: green;")
        # GROUP BOX (DELET EXPENSES AND INCOME)
        self.groupBoxType = QGroupBox(widget)
        self.groupBoxType.setObjectName(u"groupBox")
        self.groupBoxType.setGeometry(QRect(1200, 200, 480, 300))
        self.groupBoxType.setStyleSheet(u"font-size: 30px;")
        # ROW DELET
        self.RowDelet = QSpinBox(self.groupBoxType)
        self.RowDelet.setGeometry(QRect(250, 80, 200, 50))
        self.RowDelet.setMaximum(1000000)
        self.RowDelet.setMinimum(2)
        # BUTTON FOR DELETE EXPENSES OR INCOME
        self.DeletBtn = QPushButton(self.groupBoxType)
        self.DeletBtn.setGeometry(QRect(140, 210, 220, 70))
        self.DeletBtn.setStyleSheet(u"background: lightgreen;\n""color: white;\n""font-size: 40px;")
        # ROW LABEL
        self.RowLabel = QLabel(self.groupBoxType)
        self.RowLabel.setGeometry(QRect(30, 80, 200, 50))
        self.RowLabel.setStyleSheet(u"font-size: 30px;")
        # GROUP BOX (ADD EXPENSES)
        self.groupBox = QGroupBox(widget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(1200, 560, 480, 600))
        self.groupBox.setStyleSheet(u"font-size: 30px;")
        # ADD BUTTON
        self.Add = QPushButton(self.groupBox)
        self.Add.setObjectName(u"Add")
        self.Add.setGeometry(QRect(110, 480, 230, 110))
        self.Add.setStyleSheet(u"background-color: lightgreen;\n""color: white;\n""font-size: 50px;")
        # PRICE LABEL
        self.PriceLabel = QLabel(self.groupBox)
        self.PriceLabel.setObjectName(u"PriceLabel")
        self.PriceLabel.setGeometry(QRect(20, 50, 70, 31))
        self.PriceLabel.setStyleSheet(u"font-size: 30px;")
        # PRICE ENTERY
        self.PriceEntery = QLineEdit(self.groupBox)
        self.PriceEntery.setObjectName(u"PticeEntery")
        self.PriceEntery.setGeometry(QRect(200, 40, 200, 50))
        self.PriceEntery.setTabletTracking(False)
        self.PriceEntery.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.PriceEntery.setAutoFillBackground(False)
        self.PriceEntery.setFrame(True)
        self.PriceEntery.setEchoMode(QLineEdit.Normal)
        self.PriceEntery.setCursorPosition(0)
        self.PriceEntery.setDragEnabled(False)
        self.PriceEntery.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.PriceEntery.setClearButtonEnabled(False)
        # PRODUCT LABEL
        self.ProductLabel = QLabel(self.groupBox)
        self.ProductLabel.setObjectName(u"PriceLabel")
        self.ProductLabel.setGeometry(QRect(20, 135, 100, 31))
        self.ProductLabel.setStyleSheet(u"font-size: 30px;")
        # PRODUCT ENTERY
        self.ProductEntery = QLineEdit(self.groupBox)
        self.ProductEntery.setObjectName(u"PticeEntery")
        self.ProductEntery.setGeometry(QRect(200, 125, 200, 50))
        self.ProductEntery.setTabletTracking(False)
        self.ProductEntery.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.ProductEntery.setAutoFillBackground(False)
        self.ProductEntery.setFrame(True)
        self.ProductEntery.setEchoMode(QLineEdit.Normal)
        self.ProductEntery.setCursorPosition(0)
        self.ProductEntery.setDragEnabled(False)
        self.ProductEntery.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.ProductEntery.setClearButtonEnabled(False)
        # TYPE LABEL
        self.TypeLabel = QLabel(self.groupBox)
        self.TypeLabel.setObjectName(u"TypeLabel")
        self.TypeLabel.setGeometry(QRect(20, 200, 70, 40))
        self.TypeLabel.setStyleSheet(u"font-size: 30px;")
        # TYPE ENTERY
        self.TypeEntery = QComboBox(self.groupBox)
        self.TypeEntery.setObjectName(u"TypeEntery")
        self.TypeEntery.setGeometry(QRect(200, 200, 200, 40))
        self.TypeEntery.addItem("продукты")
        self.TypeEntery.addItem("транспорт")
        self.TypeEntery.addItem("развлечения")
        self.TypeEntery.addItem("техника")
        self.TypeEntery.addItem("одежда")
        self.TypeEntery.addItem("учёба")
        self.TypeEntery.addItem("книги")
        self.TypeEntery.addItem("другое")
        # DATE LABEL
        self.DateLabel = QLabel(self.groupBox)
        self.DateLabel.setObjectName(u"DateLabel")
        self.DateLabel.setGeometry(QRect(20, 270, 70, 31))
        self.DateLabel.setStyleSheet(u"font-size: 30px;")
         # DATE ENTERY
        self.DateEntery = QDateEdit(self.groupBox)
        self.DateEntery.setObjectName(u"DateEntery")
        self.DateEntery.setGeometry(QRect(200, 270, 200, 40))
        self.DateEntery.setDate(QDate(now.year, now.month, now.day))
        self.retranslateUi(widget)

        QMetaObject.connectSlotsByName(widget)
    # setupUi

    def retranslateUi(self, widget):
        widget.setWindowTitle(QCoreApplication.translate("widget", u"Бухгалтерия", None))#if QT_CONFIG(whatsthis)
        widget.setWhatsThis(QCoreApplication.translate("widget", u"<html><head/><body><p align=\"center\">wdas</p></body></html>", None))#endif // QT_CONFIG(whatsthis)

        __sortingEnabled = self.tableExpenses.isSortingEnabled()
        self.tableExpenses.setSortingEnabled(False)
        self.tableExpenses.setSortingEnabled(__sortingEnabled)

        self.chartBtn.setText(QCoreApplication.translate("widget", u"Диаграмма", None))
        #self.incomeBtn.setText(QCoreApplication.translate("widget", u"Доходы", None))
        self.TotalLabel.setText(QCoreApplication.translate("widget", u"Итоговй расход: ", None))
        self.TotalLabel_2.setText(QCoreApplication.translate("widget", u"Итог:  ", None))
        self.groupBoxType.setTitle(QCoreApplication.translate("widget", u"Удалить Расход", None))
        self.DeletBtn.setText(QCoreApplication.translate("widget", u"Удалить", None))
        self.RowLabel.setText(QCoreApplication.translate("widget", u"Строка", None))
        self.groupBox.setTitle(QCoreApplication.translate("widget", u"Добавить Расход", None))
        self.Add.setText(QCoreApplication.translate("widget", u"Add", None))
        self.TypeLabel.setText(QCoreApplication.translate("widget", u"Type", None))
        self.PriceLabel.setText(QCoreApplication.translate("widget", u"Price", None))
        self.ProductLabel.setText(QCoreApplication.translate("widget", u"Product", None))
        self.PriceEntery.setInputMask("")
        self.PriceEntery.setText("")
        self.DateLabel.setText(QCoreApplication.translate("widget", u"Date", None))