from PyQt5 import QtGui, QtCore, QtWidgets
from PyQt5.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,QPixmap, QRadialGradient)
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QTableWidget, QTableWidgetItem, QGroupBox, QComboBox, QDateEdit, QLineEdit, QTabWidget, QSpinBox, QVBoxLayout
from datetime import datetime


class Ui_Form(object):
    def setupUi(self, widget):
        now = datetime.now()
        widget.resize(2000, 1200)
        widget.setWindowIcon(QIcon("icons/bookkeeping.ico"))
        widget.setToolTipDuration(-1)
        widget.setStyleSheet("QPushButton:hover{\n""background-color: silver;\n""}")
        # SHOW CHART BUTTON
        self.chartBtn = QPushButton(widget)
        self.chartBtn.setGeometry(1620, 20, 250, 110)
        self.chartBtn.setStyleSheet("background: lightgreen;\n""color: white;\n""font-size: 40px;")
        self.chartBtn.setText("Диаграмма")
        # SELECT TYPES CHARTS
        self.TypesCharts = QComboBox(widget)
        self.TypesCharts.setGeometry(1650, 150, 200, 40)
        self.TypesCharts.setStyleSheet("font-size: 30px;")
        self.TypesCharts.addItem("общая")
        self.TypesCharts.addItem("по времени")
        self.TypesCharts.addItem("по типам")
        self.TypesCharts.addItem("по продуктам")
        # TAB WIDGET EXPENSES AND INCOME
        self.MainTab = QTabWidget(widget)
        self.MainTab.setGeometry(1,10,1480,1110)
        # TEBLE EXPENSES
        self.tableExpenses = QTableWidget(widget)
        self.tableExpenses.setGeometry(5, 5, 1480, 1110)
        self.tableExpenses.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableExpenses.setAutoScroll(True)
        self.tableExpenses.setRowCount(1000)
        self.tableExpenses.setColumnCount(5)
        self.tableExpenses.horizontalHeader().setDefaultSectionSize(270)
        self.tableExpenses.verticalHeader().setDefaultSectionSize(50)
        self.tableExpenses.setStyleSheet(u"font-size: 30px;")
        self.tableExpenses.setHorizontalHeaderLabels(('Сумма', 'Продукт', 'Дата', 'Тип', 'Источник'))
        # TEBLE INCOME
        self.tableIncome = QTableWidget(widget)
        self.tableIncome.setGeometry(5, 5, 1480, 1110)
        self.tableIncome.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableIncome.setAutoScroll(True)
        self.tableIncome.setRowCount(1000)
        self.tableIncome.setColumnCount(5)
        self.tableIncome.horizontalHeader().setDefaultSectionSize(270)
        self.tableIncome.verticalHeader().setDefaultSectionSize(50)
        self.tableIncome.setStyleSheet(u"font-size: 30px;")
        self.tableIncome.setHorizontalHeaderLabels(('Сумма', 'Продукт', 'Дата', 'Тип', 'Источник'))

        self.tableGave = QTableWidget(widget)
        self.tableGave.setGeometry(5, 5, 1480, 1110)
        self.tableGave.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableGave.setAutoScroll(True)
        self.tableGave.setRowCount(1000)
        self.tableGave.setColumnCount(4)
        self.tableGave.horizontalHeader().setDefaultSectionSize(338)
        self.tableGave.verticalHeader().setDefaultSectionSize(50)
        self.tableGave.setStyleSheet(u"font-size: 30px;")
        self.tableGave.setHorizontalHeaderLabels(('Сумма', 'Кому', 'Когда', 'Вернули'))

        self.tableTook = QTableWidget(widget)
        self.tableTook.setGeometry(5, 5, 1480, 1110)
        self.tableTook.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableTook.setAutoScroll(True)
        self.tableTook.setRowCount(1000)
        self.tableTook.setColumnCount(4)
        self.tableTook.horizontalHeader().setDefaultSectionSize(338)
        self.tableTook.verticalHeader().setDefaultSectionSize(50)
        self.tableTook.setStyleSheet(u"font-size: 30px;")
        self.tableTook.setHorizontalHeaderLabels(('Сумма', 'У кого', 'Когда', 'Использовал'))
        # ADD TAB TO TabWidget FOR EXPENSES AND INCOME
        self.MainTab.addTab(self.tableExpenses, "Расходы")
        self.MainTab.addTab(self.tableIncome, "Доходы")
        self.MainTab.addTab(self.tableTook, "Взял")
        self.MainTab.addTab(self.tableGave, "Дал")
        # TOTAL EXPENSES AND INCOME LABEL
        self.TotalLabel = QLabel(widget)
        self.TotalLabel.setGeometry(10, 1130, 1000, 60)
        self.TotalLabel.setStyleSheet("font-size: 39px;")
        self.TotalLabel.setText("Итоговй расход: ")
        # TOTAL LABEL 
        self.TotalLabel_2 = QLabel(widget)
        self.TotalLabel_2.setGeometry(550, 1130, 1000, 60)
        self.TotalLabel_2.setStyleSheet("font-size: 39px;")
        self.TotalLabel_2.setText("Итог:  ")

        self.percentTotalLabel = QLabel(widget)
        self.percentTotalLabel.setGeometry(850, 1130, 1000, 60)
        self.percentTotalLabel.setStyleSheet("font-size: 39px;\n""color: green;")
        # GROUP BOX (DELET EXPENSES AND INCOME)
        self.groupBoxType = QGroupBox(widget)
        self.groupBoxType.setGeometry(1500, 200, 480, 300)
        self.groupBoxType.setStyleSheet("font-size: 30px;")
        # ROW DELET
        self.RowDelet = QSpinBox(self.groupBoxType)
        self.RowDelet.setGeometry(250, 80, 200, 50)
        self.RowDelet.setMaximum(1000000)
        self.RowDelet.setMinimum(1)
        # BUTTON FOR DELETE EXPENSES OR INCOME
        self.DeletBtn = QPushButton(self.groupBoxType)
        self.DeletBtn.setGeometry(140, 210, 220, 70)
        self.DeletBtn.setStyleSheet("background: lightgreen;\n""color: white;\n""font-size: 40px;")
        self.DeletBtn.setText("Удалить")
        # ROW LABEL
        self.RowLabel = QLabel(self.groupBoxType)
        self.RowLabel.setGeometry(30, 80, 200, 50)
        self.RowLabel.setStyleSheet("font-size: 30px;")
        # GROUP BOX (ADD EXPENSES)
        self.groupBox = QGroupBox(widget)
        self.groupBox.setGeometry(1500, 560, 480, 600)
        self.groupBox.setStyleSheet("font-size: 30px;")
        self.groupBox.setTitle("Удалить Расход")
        # ADD BUTTON
        self.Add = QPushButton(self.groupBox)
        self.Add.setGeometry(110, 480, 230, 110)
        self.Add.setStyleSheet("background-color: lightgreen;\n""color: white;\n""font-size: 50px;")
        self.Add.setText("Добавить")
        # PRICE LABEL
        self.PriceLabel = QLabel(self.groupBox)
        self.PriceLabel.setGeometry(20, 50, 130, 31)
        self.PriceLabel.setStyleSheet("font-size: 30px;")
        # PRICE ENTERY
        self.PriceEntery = QLineEdit(self.groupBox)
        self.PriceEntery.setGeometry(200, 40, 200, 50)
        self.PriceEntery.setTabletTracking(False)
        self.PriceEntery.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.PriceEntery.setAutoFillBackground(False)
        self.PriceEntery.setFrame(True)
        self.PriceEntery.setEchoMode(QLineEdit.Normal)
        self.PriceEntery.setCursorPosition(0)
        self.PriceEntery.setDragEnabled(False)
        self.PriceEntery.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.PriceEntery.setClearButtonEnabled(False)
        # PRODUCT LABEL
        self.ProductLabel = QLabel(self.groupBox)
        self.ProductLabel.setGeometry(20, 135, 130, 31)
        self.ProductLabel.setStyleSheet("font-size: 30px;")
        # PRODUCT ENTERY
        self.ProductEntery = QLineEdit(self.groupBox)
        self.ProductEntery.setGeometry(200, 125, 200, 50)
        self.ProductEntery.setTabletTracking(False)
        self.ProductEntery.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.ProductEntery.setAutoFillBackground(False)
        self.ProductEntery.setFrame(True)
        self.ProductEntery.setEchoMode(QLineEdit.Normal)
        self.ProductEntery.setCursorPosition(0)
        self.ProductEntery.setDragEnabled(False)
        self.ProductEntery.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.ProductEntery.setClearButtonEnabled(False)
        # TYPE LABEL
        self.TypeLabel = QLabel(self.groupBox)
        self.TypeLabel.setGeometry(20, 200, 130, 40)
        self.TypeLabel.setStyleSheet("font-size: 30px;")
        # TYPE ENTERY
        self.TypeEntery = QComboBox(self.groupBox)
        self.TypeEntery.setGeometry(200, 200, 200, 40)
        self.TypeEntery.addItem("продукты")
        self.TypeEntery.addItem("транспорт")
        self.TypeEntery.addItem("развлечения")
        self.TypeEntery.addItem("техника")
        self.TypeEntery.addItem("одежда")
        self.TypeEntery.addItem("учёба")
        self.TypeEntery.addItem("книги")
        self.TypeEntery.addItem("другое")
        # DATE LABEL
        self.DateLabel = QLabel(self.groupBox)
        self.DateLabel.setGeometry(20, 270, 130, 31)
        self.DateLabel.setStyleSheet("font-size: 30px;")
         # DATE ENTERY
        self.DateEntery = QDateEdit(self.groupBox)
        self.DateEntery.setGeometry(200, 270, 200, 40)
        self.DateEntery.setDate(QDate(now.year, now.month, now.day))

        self.sourceLabel = QLabel(self.groupBox)
        self.sourceLabel.setGeometry(20, 350, 130, 31)
        self.sourceLabel.setText("Источник")

        self.sourceEntery = QComboBox(self.groupBox)
        self.sourceEntery.setGeometry(200, 350, 200, 40)
        self.sourceEntery.addItem("мои деньги")

        self.retranslateUi(widget)

        QMetaObject.connectSlotsByName(widget)
    # setupUi

    def retranslateUi(self, widget):
        widget.setWindowTitle(QCoreApplication.translate("widget", u"Бухгалтерия", None))
#if QT_CONFIG(whatsthis)
        widget.setWhatsThis(QCoreApplication.translate("widget", u"<html><head/><body><p align=\"center\">wdas</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        __sortingEnabled = self.tableExpenses.isSortingEnabled()
        self.tableExpenses.setSortingEnabled(False)
        self.tableExpenses.setSortingEnabled(__sortingEnabled)

        self.RowLabel.setText(QCoreApplication.translate("widget", u"Строка", None))
        self.groupBox.setTitle(QCoreApplication.translate("widget", u"Добавить Расход", None))
        self.TypeLabel.setText(QCoreApplication.translate("widget", u"Тип", None))
        self.PriceLabel.setText(QCoreApplication.translate("widget", u"Сумма", None))
        self.ProductLabel.setText(QCoreApplication.translate("widget", u"Продукт", None))
        self.DateLabel.setText(QCoreApplication.translate("widget", u"Дата", None))